### ISSUE TITLE
Main window full size, but still fails to show any devices

### ISSUE THREAD

**Issue by gentlesystems** [jnross/Bluetility#10] opened 2020-07-21 21:19 UTC
macOS 10.14.6
Bluetility 1.3 (6)

The main window opens up full size (not like the previous Mojave error) but no devices are listed.  At startup and when hitting Refresh, the console reports:
`API MISUSE: <CBCentralManager: 0x6000019479c0> can only accept this command while in the powered on state`

I am, of course, surrounded by bluetooth devices, and I'm connected to a bluetooth mouse.

**Comment by jnross** [comment] 2020-07-23 04:14
Hmm, someone else reported a similar problem, but I'm unable to reproduce this issue.  I'm testing using a MacBook Pro (Retina, 15-inch, Late 2013), a.k.a. `MacBookPro11,3`, running Mojave 10.14.6:
<img width="698" alt="Screen Shot 2020-07-22 at 9 07 56 PM" src="https://user-images.githubusercontent.com/798990/88251446-b0e55380-cc5f-11ea-95ce-2a9c95c22dec.png">
Here is a screenshot of Bluetility happily finding devices while running on this machine:
<img width="1359" alt="Screen Shot 2020-07-22 at 9 09 04 PM" src="https://user-images.githubusercontent.com/798990/88251475-c195c980-cc5f-11ea-9fc2-3f0822379083.png">
I also checked in Console and see no occurrences of the `API MISUSE` message mentioned in the description.

Perhaps you could provide some additional information about your specific hardware that might help to isolate this problem.  Also, can you try other BLE scanning apps and let me know what behavior they exhibit?  For example, [BlueSee](https://apps.apple.com/us/app/bluesee-ble-debugger/id1336679524?mt=12):
<img width="1487" alt="Screen Shot 2020-07-22 at 9 13 47 PM" src="https://user-images.githubusercontent.com/798990/88251643-4b459700-cc60-11ea-8763-eb86e8b53a5c.png">

**Comment by gentlesystems** [comment] 2020-07-24 00:06
After failing to see anything with BlueSee, and after poking around a bit, I suspect that my bluetooth hardware is not supported.  I'm on a Mac Pro 5,1, and it seems BLE support is limited, despite it connecting to all of my devices fine.  I appreciate you looking into this and the information you provided.

**Comment by jnross** [comment] 2020-07-24 04:06
And old cheese grater! Wow! Thanks for providing additional information.  It may be possible that you can purchase a USB Bluetooth dongle that would be supported for operations like this.  Seems surprising that Apple wouldn't have CoreBluetooth support for hardware like this, but I suppose they do push aggressive towards the future, sometimes leaving older hardware stranded.

**Comment by jnross** [comment] 2020-07-24 04:07
I suppose the other thing I would mention is that it is usual for Bluetooth hardware like mice and keyboards to use Bluetooth Classic, not BLE, and devices like that are often not detectable via CoreBluetooth.

**Comment by jnross** [comment] 2020-10-04 15:14
Closing, since it seems the MacPro5,1 has very limited support for CoreBluetooth.

**Closed as completed by jnross** 2020-10-04 15:14 UTC
